name: Keep dependencies up-to-date

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: keepitsecret
          POSTGRES_USER: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://testdb:keepitsecret@localhost:5432/testdb
    steps:
      - uses: textbook/take-action@nodejs
        with:
          node-version: 20
      - uses: textbook/take-action@playwright
      - run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
      - run: ./bin/up-to-date.sh
